version: '3.9'

services:
  shuffle:
    image: frikky/shuffle:latest
    container_name: shuffle
    ports:
      - "3001:3001"
    environment:
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password
    volumes:
      - shuffle-data:/data

volumes:
  shuffle-data:
