global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.18.0.102:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['172.18.0.103:8080']
